import { Component } from '@angular/core';
import { HeaderComponent } from '@/widgets/header/header.component';
import { ProductsGridComponent } from '@/widgets/products-grid/products-grid.component';
import { FooterComponent } from '@/widgets/footer/footer.component';
import type { Product } from '@/entities/product';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [HeaderComponent, ProductsGridComponent, FooterComponent],
  templateUrl: './index.page.html',
})
export default class Home {
  protected readonly products: Product[] = [
    {
      id: 1,
      title: 'Надувной бассейн LanPass',
      description: 'Комфортный бассейн для всей семьи, простой в установке и уходе.',
      text: 'Комфортный бассейн для всей семьи, простой в установке и уходе.',
      brand: 'LanPass',
      category_id: 1,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      deletedAt: {
        time: new Date().toISOString(),
        valid: false,
      },
      is_active: true,
      is_manual: false,
      photo_url: '/LanPass.png',
      price: 129990,
      quantity: 10,
      sku: 'LP-POOL-001',
      weight: 5,
    },
    {
      id: 2,
      title: 'Кресло-реклайнер LanPass',
      description: 'Эргономичное кресло для расслабления после трудного дня.',
      text: 'Эргономичное кресло для расслабления после трудного дня.',
      brand: 'LanPass',
      category_id: 2,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      deletedAt: {
        time: new Date().toISOString(),
        valid: false,
      },
      is_active: true,
      is_manual: false,
      photo_url: '/LanPass.png',
      price: 89990,
      quantity: 5,
      sku: 'LP-CHAIR-001',
      weight: 3,
    }, {
      id: 1,
      title: 'Надувной бассейн LanPass',
      description: 'Комфортный бассейн для всей семьи, простой в установке и уходе.',
      text: 'Комфортный бассейн для всей семьи, простой в установке и уходе.',
      brand: 'LanPass',
      category_id: 1,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      deletedAt: {
        time: new Date().toISOString(),
        valid: false,
      },
      is_active: true,
      is_manual: false,
      photo_url: '/LanPass.png',
      price: 129990,
      quantity: 10,
      sku: 'LP-POOL-001',
      weight: 5,
    },
    {
      id: 2,
      title: 'Кресло-реклайнер LanPass',
      description: 'Эргономичное кресло для расслабления после трудного дня.',
      text: 'Эргономичное кресло для расслабления после трудного дня.',
      brand: 'LanPass',
      category_id: 2,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      deletedAt: {
        time: new Date().toISOString(),
        valid: false,
      },
      is_active: true,
      is_manual: false,
      photo_url: '/LanPass.png',
      price: 89990,
      quantity: 5,
      sku: 'LP-CHAIR-001',
      weight: 3,
    }, {
      id: 1,
      title: 'Надувной бассейн LanPass',
      description: 'Комфортный бассейн для всей семьи, простой в установке и уходе.',
      text: 'Комфортный бассейн для всей семьи, простой в установке и уходе.',
      brand: 'LanPass',
      category_id: 1,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      deletedAt: {
        time: new Date().toISOString(),
        valid: false,
      },
      is_active: true,
      is_manual: false,
      photo_url: '/LanPass.png',
      price: 129990,
      quantity: 10,
      sku: 'LP-POOL-001',
      weight: 5,
    },
    {
      id: 2,
      title: 'Кресло-реклайнер LanPass',
      description: 'Эргономичное кресло для расслабления после трудного дня.',
      text: 'Эргономичное кресло для расслабления после трудного дня.',
      brand: 'LanPass',
      category_id: 2,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      deletedAt: {
        time: new Date().toISOString(),
        valid: false,
      },
      is_active: true,
      is_manual: false,
      photo_url: '/LanPass.png',
      price: 89990,
      quantity: 5,
      sku: 'LP-CHAIR-001',
      weight: 3,
    },
  ];
}
